UDIS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name = 'home'),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', views.home, name = 'home'),
    path('projects/', include('projects.urls')),
    path('inven/', include('inventory.urls')),
    path('pubs/', include('publications.urls')),
    path('accounts/', include('accountings.urls')),
    path('courses/', include('courses.urls'))
]

inventory/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('inventory/', views.inventory, name = 'allinv'),
    path('inventory/addinv/', views.InventoryCreate.as_view(), name = 'addinv'),
    path('inventory/update/<int:pk>/', views.InventoryUpdate.as_view(), name = 'update'),
    path('inventory/search/', views.inv_searcher, name = 'invsearch'),
    path('inventory/search-results/', views.InventorySearch.as_view(), name = 'search_inv_result'),
]

inventory/models.py
from django.db import models

# Create your models here.

class Inventory(models.Model):
    """
    A class of models that stores the furniture iventory of the department.
    """

    dept_name = models.CharField(max_length = 200)
    furniture_name = models.CharField(max_length = 200, unique = True)
    furniture_type = models.CharField(max_length = 200)
    price = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    location = models.CharField(max_length = 200)

inventory/forms.py
from django import forms
from .models import Inventory

class InventoryForm(forms.ModelForm):
    '''
    A form to enter the details of a new furniture type
    '''

    furniture_name = forms.CharField(max_length = 200, required = True, widget=forms.TextInput(attrs={'placeholder': 'Furniture Name'})) #Name of the inven
    dept_name = forms.CharField(max_length = 200, required = True, widget=forms.TextInput(attrs={'placeholder': 'Department Name'})) #For the storage of different department names.
    furniture_type = forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'placeholder': 'Furniture Type'})) #The head of the inven, whom a student has to contact.
    price = forms.IntegerField(min_value = 0, required = True, widget=forms.TextInput(attrs={'placeholder': 'Price (in Rs)'}))
    quantity = forms.IntegerField(min_value = 0, required = True, widget=forms.TextInput(attrs={'placeholder': 'Quantity'}))
    location = forms.CharField(max_length = 200, required = True, widget=forms.TextInput(attrs={'placeholder': 'Location'})) #Name of the location

    class Meta:

        model = Inventory
        fields = '__all__'

    def save(self):

        inven = super(InventoryForm, self).save(commit = False)

        inven.furniture_name = self.cleaned_data.get('furniture_name')
        inven.dept_name = self.cleaned_data.get('dept_name')
        inven.furniture_type = self.cleaned_data.get('furniture_type')
        inven.price = self.cleaned_data.get('price')
        inven.quantity = self.cleaned_data.get('quantity')
        inven.location = self.cleaned_data.get('location')

        try:
            inven.save()

        except Exception:

            Inventory.objects.filter(id = inven.id).delete()
            inven.save()

        return inven

projects/forms.py
from django import forms
from .models import Projects

class ProjectForm(forms.ModelForm):
    '''
    A form to enter the details of a new department project/research 
    '''

    project_name = forms.CharField(max_length = 200, required = True, widget=forms.TextInput(attrs={'placeholder': 'Project Name'})) #Name of the project
    dept_name = forms.CharField(max_length = 100, required = True, widget=forms.TextInput(attrs={'placeholder': 'Department Name'})) #For the storage of different department names.
    faculty_name = forms.CharField(max_length = 100, widget=forms.TextInput(attrs={'placeholder': 'Faculty Name'})) #The head of the project, whom a student has to contact.
    status = forms.ChoiceField(choices = Projects.STATUS_CHOICES, required = True)
    
    duration_year = forms.IntegerField(required = True, widget=forms.TextInput(attrs={'placeholder': 'Enter yearly duration'}))
    duration_month = forms.ChoiceField(choices = Projects.MONTH_CHOICES, required = True)
    allocated_funds = forms.IntegerField(min_value = 0, required = True)

    class Meta:

        model = Projects
        fields = '__all__'

    def save(self):

        project = super(ProjectForm, self).save(commit = False)

        project.project_name = self.cleaned_data.get('project_name')
        project.dept_name = self.cleaned_data.get('dept_name')
        project.faculty_name = self.cleaned_data.get('faculty_name')
        project.status = self.cleaned_data.get('status')
        project.duration_year = self.cleaned_data.get('duration_year')
        project.duration_month = self.cleaned_data.get('duration_month')
        project.allocated_funds = self.cleaned_data.get('allocated_funds')

        try:
            project.save()

        except Exception:

            Projects.objects.filter(id = project.id).delete()
            project.save()

        return project

inventory/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView, ListView
from datetime import date

from .forms import InventoryForm
from .models import Inventory
from accountings.models import Accounts

# Create your views here.

def inventory(request):
    inven = Inventory.objects.all()
    return render(request, 'inventory/invlist.html', {'inventory': inven})

def inv_searcher(request):
    return render(request, 'inventory/invsearch.html')


class InventoryCreate(CreateView):

    model = Inventory
    form_class = InventoryForm
    template_name = 'inventory/addinv.html'

    def form_valid(self, form):
        
        dept_bal = Accounts.objects.filter(dept_name = form.cleaned_data['dept_name']).last().current_balance
        funds_reqd = form.cleaned_data['price'] * form.cleaned_data['quantity']
        
        if dept_bal < funds_reqd:

            messages.error(self.request, "Ouch! There aren't enough funds to allocate to the project!")
            return redirect(self.request.path)
        
        user = self.request.user
        inven = form.save()

        Accounts.objects.create(
            dept_name = inven.dept_name,
            amount = funds_reqd,
            transaction_type = 'D',
            transactee = f"Secretary {user.username}",
            purpose = f"Furniture {inven.furniture_name} allocation",
            date_of_transaction = date.today(),
            current_balance = dept_bal - funds_reqd
            )

        if inven:
            messages.success(self.request, f'Furniture {inven.furniture_name} added successfully!')
            return redirect('allinv')
        
class InventoryUpdate(UpdateView):

    model = Inventory
    form_class = InventoryForm
    template_name = 'inventory/addinv.html'

    def form_valid(self, form):

        dept_bal = Accounts.objects.filter(dept_name = form.cleaned_data['dept_name']).last().current_balance
        
        user = self.request.user
        pk = self.kwargs['pk']
        inven = Inventory.objects.filter(id = pk).first()

        if inven.dept_name != user.dept_name:
            messages.error(self.request, 'Can not edit the inventories of another department!')
            return inventory(self.request)
        
        if 'price' in form.changed_data or 'quantity' in form.changed_data:

            acc = Accounts.objects.filter(purpose = f"Furniture {inven.furniture_name} allocation").last()
            funds_reqd = form.cleaned_data['price'] * form.cleaned_data['quantity']
            extra_funds = funds_reqd - acc.amount

            if dept_bal < extra_funds:

                messages.error(self.request, "Ouch! There aren't enough funds to allocate to the project!")
                return redirect(self.request.path)
            
            Accounts.objects.create(
                dept_name = inven.dept_name,
                amount = funds_reqd,
                transaction_type = 'D',
                transactee = f"Secretary {user.username}",
                purpose = f"Furniture {inven.furniture_name} allocation",
                date_of_transaction = date.today(),
                current_balance = dept_bal - extra_funds
                )
        
        inven = form.save()

        if inven:
            messages.success(self.request, f'Furniture {inven.furniture_name} updated successfully!')
            return redirect('allinv')
        
class InventorySearch(ListView):

    model = Inventory
    template_name = 'inventory/invlist.html'
    context_object_name = 'inventory'

    def get_queryset(self):
        
        fur_name = self.request.GET.get('fur_name')
        fur_type = self.request.GET.get('fur_type')
        
        if fur_name == '':
            if fur_type == '':
                inventory = Inventory.objects.all()
            
            else:
                inventory = Inventory.objects.filter(furniture_type = fur_type)
        else:
            if fur_type == '':
                inventory = Inventory.objects.filter(furniture_name__contains = fur_name)
            
            else:
                inventory = Inventory.objects.filter(furniture_name__contains = fur_name, furniture_type = fur_type)
        return inventory

templates/inventory/addinv.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% if not user.is_secretary %} 
    <meta http-equiv="refresh" content="0; URL={% url 'allinv' %}" />
    {% endif %}

    <title>Add Project</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/proj-style.css' %}">
</head>

<body>
    <div class="container">
        
        <form method="POST" class = "project">
            
            {% csrf_token %}
            
            <label for="id_project_name">Furniture name:</label>
            
            {{ form.furniture_name }}
            {{ form.furniture_name.errors }}
    
            <label for="id_dept_name">Department name:</label>

            {{ form.dept_name }}
            {{ form.dept_name.errors }}

            <label for="id_faculty_name">Furniture Type:</label>

            {{ form.furniture_type }}
            {{ form.furniture_type.errors }}
            
            <label for="id_status">Price:</label>
            
            {{ form.price }}
            {{ form.price.errors }}
    
            <label for="id_duration_year">Quantity:</label>
    
            {{ form.quantity }}
            {{ form.quantity.errors }}

            <label for="id_duration_month">Location:</label>
    
            {{ form.location }}
            {{ form.location.errors }}
    
            <button type="submit" class = "submit">Submit!</button>
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}
        </form>

    </div>
</body>

</html>

templates/inventory/invlist.html
{% load static %}

<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inventory</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/proj-style.css' %}">
</head>


<body class="cont">
    <!-- <div class="cont1">
            <label><b>Project Name</b></label>
            <label><b>Faculty</b></label>
            <label><b>Status</b></label>
            <label><b>Duration</b></label></li>
        </div>

        <div class="cont2">
            <div class="proj">
                <label class = "pname"><b>P1</b></label>
                <label class = "fac"><b>F1</b></label>
                <label class = "stat"><b>Ongoing</b></label>
                <label class = "dur"><b>2yrs, 0 months</b></label>
            </div>
            <div class="proj">
                <label class = "pname"><b>P2</b></label>
                <label class = "fac"><b>F2</b></label>
                <label class = "stat"><b>Ongoing</b></label>
                <label class = "dur"><b>3yrs, 0 months</b></label>
            </div>
        </div> -->


    <div>
        <!-- Add home page link here -->
        <a href="{% url 'home' %}" class="button">Home</a>
        {% if user.is_secretary %} <a href="{% url 'addinv' %}" class="button">Add Item</a> {% endif %}
        <a href="{% url 'invsearch' %}" class="button">Search</a>
        
        <h1>Inventory</h1>
        <div class="table-container">
            
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}

            {% if inventory %}

            <table>
                <thead>
                    <tr>
                        <th>Department Name</th>
                        <th>Furniture Name</th>
                        <th>Furniture Type</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Location</th>

                        {% if user.is_secretary %} 
                            <th>Update Inventory</th>
                        {% endif %}

                    </tr>
                </thead>
                <tbody>

                    

                    {% for inven in inventory|dictsort:"dept_name" %}

                    <tr>
                        <td>{{ inven.dept_name }}</td>

                        <td>{{ inven.furniture_name }}</td>

                        <td>{{ inven.furniture_type }}</td>

                        <td>{{ inven.price }}</td>

                        <td>{{ inven.quantity }}</td>

                        <td>{{ inven.location }}</td>
                        
                        {% if user.is_secretary %} 
                            <td>
                                {% if user.dept_name == inven.dept_name %}
                                <a href="{% url 'update' inven.id %}">Update {{ inven.furniture_name }}</a>
                                {% endif %}
                            </td>
                        {% endif %}
                        
                    </tr>
                    {% endfor %}

                    

                </tbody>
            </table>
            {% else %}
                
                <p>Oops! It seems there is no data satisfying all the conditions together!</p>

            {% endif %}
        </div>
    </div>

</body>

</html>

templates/inventory/invsearch.html
{% load static %}

<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Inventory</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/proj-style.css' %}">
</head>


<body class="cont">
    <div>
        <a href="{% url 'home' %}" class="button">Home</a>
        
        <h1>Search Inventory</h1>
        <h4>Enter required search data in the fields. If blank, the specific field queries all the furniture items in the database.</h4>
        <h4><strong>Note:</strong> Furniture type searches for exact matches, while furniture name searches for substring matches. </h4>

    </div>
    <div class="container">
           
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
               
        <form action="{% url 'search_inv_result' %}" method="GET" class="project">

            <label for="id_furniture_name">Enter the object name:</label>
            <input name="fur_name" type="text" placeholder="Enter the furniture name (optional)"/>

            <label for="id_furniture_type">Enter the object type:</label>
            <input name="fur_type" type="text" placeholder="Enter the furniture type here (optional)"/>

            <button type="submit" class="submit">Submit</button>
        </form>
        
    </div>

</body>

</html>