UDIS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name = 'home'),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', views.home, name = 'home'),
    path('projects/', include('projects.urls')),
    path('inven/', include('inventory.urls')),
    path('pubs/', include('publications.urls')),
    path('accounts/', include('accountings.urls')),
    path('courses/', include('courses.urls'))
]

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('project/', views.allprojects, name = 'allprojects'),
    path('project/addprojects/', views.ProjectCreateForm.as_view(), name = 'addproject'),
    path('project/update/<int:pk>/', views.ProjectUpdate.as_view(), name = 'projupdate'),
]

projects/models.py
from django.db import models
# Create your models here.

class Projects(models.Model):
    '''
    A class of models that creates the database of projects, classified by department names.
    '''

    project_name = models.CharField(max_length = 200, unique = True) #Name of the project
    dept_name = models.CharField(max_length = 100) #For the storage of different department names.
    faculty_name = models.CharField(max_length = 100) #The head of the project, whom a student has to contact.
    
    STATUS_CHOICES = (
        ('', "Select status"),
        ('O', "Ongoing"),
        ('C', "Completed"),
    )

    status = models.CharField(max_length = 1, choices = STATUS_CHOICES, default = '')
    
    MONTH_CHOICES = tuple((m, m) for m in range(13))
    
    duration_year = models.IntegerField()
    duration_month = models.IntegerField(choices = MONTH_CHOICES, default = 0)
    allocated_funds = models.PositiveIntegerField()

projects/forms.py
from django import forms
from .models import Projects

class ProjectForm(forms.ModelForm):
    '''
    A form to enter the details of a new department project/research 
    '''

    project_name = forms.CharField(max_length = 200, required = True, widget=forms.TextInput(attrs={'placeholder': 'Project Name'})) #Name of the project
    dept_name = forms.CharField(max_length = 100, required = True, widget=forms.TextInput(attrs={'placeholder': 'Department Name'})) #For the storage of different department names.
    faculty_name = forms.CharField(max_length = 100, widget=forms.TextInput(attrs={'placeholder': 'Faculty Name'})) #The head of the project, whom a student has to contact.
    status = forms.ChoiceField(choices = Projects.STATUS_CHOICES, required = True)
    
    duration_year = forms.IntegerField(required = True, widget=forms.TextInput(attrs={'placeholder': 'Enter yearly duration'}))
    duration_month = forms.ChoiceField(choices = Projects.MONTH_CHOICES, required = True)
    allocated_funds = forms.IntegerField(min_value = 0, required = True)

    class Meta:

        model = Projects
        fields = '__all__'

    def save(self):

        project = super(ProjectForm, self).save(commit = False)

        project.project_name = self.cleaned_data.get('project_name')
        project.dept_name = self.cleaned_data.get('dept_name')
        project.faculty_name = self.cleaned_data.get('faculty_name')
        project.status = self.cleaned_data.get('status')
        project.duration_year = self.cleaned_data.get('duration_year')
        project.duration_month = self.cleaned_data.get('duration_month')
        project.allocated_funds = self.cleaned_data.get('allocated_funds')

        try:
            project.save()

        except Exception:

            Projects.objects.filter(id = project.id).delete()
            project.save()

        return project

projects/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic import CreateView, UpdateView
from datetime import date

from .forms import ProjectForm
from .models import Projects
from accountings.models import Accounts

# Create your views here.

def allprojects(request):
    projects = Projects.objects.all()
    return render(request, 'projects/plist.html', {'projects': projects})

class ProjectCreateForm(CreateView):

    model = Projects
    form_class = ProjectForm
    template_name = 'projects/addproj.html'

    def form_valid(self, form):

        dept_bal = Accounts.objects.filter(dept_name = form.cleaned_data['dept_name']).last().current_balance

        if dept_bal < form.cleaned_data['allocated_funds']:

            messages.error(self.request, "Ouch! There aren't enough funds to allocate to the project!")
            return redirect(self.request.path)
        
        user = self.request.user
        project = form.save()

        Accounts.objects.create(
            dept_name = project.dept_name,
            amount = project.allocated_funds,
            transaction_type = 'D',
            transactee = f"Secretary {user.username}",
            purpose = f"Project {project.project_name} allocation",
            date_of_transaction = date.today(),
            current_balance = dept_bal - project.allocated_funds
            )
        
        if project:
            messages.success(self.request, f'Project {project.project_name} added successfully!')
            return redirect('allprojects')
        
class ProjectUpdate(UpdateView):

    model = Projects
    form_class = ProjectForm
    template_name = 'projects/addproj.html'

    def form_valid(self, form):

        if 'status' in form.changed_data and form.cleaned_data['status'] == 'O':
            form.cleaned_data['status'] = 'C'

        dept_bal = Accounts.objects.filter(dept_name = form.cleaned_data['dept_name']).last().current_balance

        user = self.request.user
        pk = self.kwargs['pk']
        proj = Projects.objects.filter(id = pk).first()
        
        if proj.dept_name != user.dept_name:
            messages.error(self.request, 'Can not edit the projects of another department!')
            return allprojects(self.request)

        if 'allocated_funds' in form.changed_data:

            acc = Accounts.objects.filter(purpose = f"Project {proj.project_name} allocation").last()
            extra_funds = form.cleaned_data['allocated_funds'] - acc.amount

            if dept_bal < extra_funds:

                messages.error(self.request, "Ouch! There aren't enough funds to allocate to the project!")
                return redirect(self.request.path)
            
            Accounts.objects.create(
                dept_name = proj.dept_name,
                amount = form.cleaned_data['allocated_funds'],
                transaction_type = 'D',
                transactee = f"Secretary {user.username}",
                purpose = f"Project {proj.project_name} allocation",
                date_of_transaction = date.today(),
                current_balance = dept_bal - extra_funds
                )
        
        project = form.save()
        
        if project:
            messages.success(self.request, f'Project {project.project_name} updated successfully!')
            return redirect('allprojects')

templates/projects/addproj.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% if not user.is_secretary %} 
    <meta http-equiv="refresh" content="0; URL={% url 'allprojects' %}" />
    {% endif %}
    
    <title>Add Project</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/proj-style.css' %}">
</head>

<body>
    <div class="container">

        <form method="POST" class = "project">
            
            {% csrf_token %}
            
            <label for="id_project_name">Project name:</label>
            
            {{ form.project_name }}
            {{ form.project_name.errors }}
    
            <label for="id_dept_name">Department name:</label>

            {{ form.dept_name }}
            {{ form.dept_name.errors }}

            <label for="id_faculty_name">Faculty name:</label>

            {{ form.faculty_name }}
            {{ form.faculty_name.errors }}
            
            {% if form.status %}
            <label for="id_status">Status:</label>
            
            {{ form.status }}
            {{ form.status.errors }}
            
            {% endif %}
            <label for="id_funds">Allocated Budget:</label>

            {{ form.allocated_funds }}
            {{ form.allocated_funds.errors }}
    
            <label for="id_duration_year">Duration (Years):</label>
    
            {{ form.duration_year }}
            {{ form.duration_year.errors }}

            <label for="id_duration_month">Duration (Months):</label>
    
            {{ form.duration_month }}
            {{ form.duration_month.errors }}
    
            <button type="submit" class = "submit">Submit!</button>

            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}
        </form>
    </div>
</body>

</html>

templates/projects/plist.html
{% load static %}

<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projects</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/proj-style.css' %}">
</head>


<body class="cont">

    <div>
        <a href="{% url 'home' %}" class="button">Home</a>
        {% if user.is_secretary %} <a href="{% url 'addproject' %}" class="button">Add Project</a> {% endif %}

        <h1>Projects</h1>
        <div class="table-container">
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}

            {% regroup projects|dictsort:"faculty_name"|dictsort:"dept_name" by dept_name as project_list %}

            <table>
                <thead>
                    <tr>
                        <th>Department Name</th>
                        <th>Project Name</th>
                        <th>Faculty</th>
                        <th>Status</th>
                        <th>Allocated Buudget</th>
                        <th>Duration</th>

                        {% if user.is_secretary %} 
                            <th>Update Project</th>
                        {% endif %}

                    </tr>
                </thead>
                <tbody>

                    {% for project_group in project_list %}

                        {% for project in project_group.list %}

                        <tr>
                            <td>{{ project_group.grouper }}</td>

                            <td>{{ project.project_name }}</td>

                            <td>{{ project.faculty_name }}</td>

                            <td>{{ project.get_status_display }}</td>

                            <td>{{ project.allocated_funds }}</td>
                            
                            <td>{{ project.duration_year }} yrs, {{ project.duration_month }} months</td>
                            
                            {% if user.is_secretary %} 
                                <td>
                                    {% if user.dept_name == project.dept_name %}
                                    <a href="{% url 'projupdate' project.id %}">Update {{ project.project_name }}</a>
                                    {% endif %}
                                </td>
                            {% endif %}

                        </tr>

                        {% endfor %}
                    {% endfor %}
                    
                </tbody>
            </table>
        
        </div>
    </div>

</body>

</html>