UDIS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name = 'home'),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', views.home, name = 'home'),
    path('projects/', include('projects.urls')),
    path('inven/', include('inventory.urls')),
    path('pubs/', include('publications.urls')),
    path('accounts/', include('accountings.urls')),
    path('courses/', include('courses.urls'))
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    '''
    The extension of the abstractuser class, that defines boolean fields to
    distinguish between user classes. Stored as an SQL table in Postgres
    '''

    email = models.EmailField(unique = True)
    is_student = models.BooleanField(default = False)
    is_faculty = models.BooleanField(default = False)
    is_secretary = models.BooleanField(default = False)

    first_name = models.CharField(max_length = 80)
    last_name = models.CharField(max_length = 80)
    dept_name = models.CharField(max_length = 80)
    address = models.CharField(max_length = 200)

    GENDER_CHOICES = (
        ('', 'Select a gender'),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Others')
    )
    
    gender = models.CharField(max_length = 1, choices = GENDER_CHOICES, default = '')
    phone_number = models.CharField(max_length = 10)
    year_of_admission = models.PositiveIntegerField(null = True, blank = True)
    
class Student(User):
    '''
    Class Student, that extends on the defined abstract User class
    '''

    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True, related_name = 'stu')

    PROGRAMME_CHOICES = (
        ('', 'Select a Programme'),
        ('BT', "Bachelor of Technology"),
        ('MT', "Master of Technology"),
        ('PhD', "Doctor of Philosophy"),
        ('MSc', "Master of Science"),
        ('BSc', "Bachelor of Science"),
        ('DD', "Dual Degree"),
    )
    programme = models.CharField(max_length = 3, choices = PROGRAMME_CHOICES, default = '')
    guardian_name = models.CharField(max_length = 80)
    


    
    

courses/models.py
from django.db import models
from accounts.models import Student

# Create your models here.

class Courses(models.Model):
    """
    Class Courses, to store details of the various courses offered by the institute.
    """
    course_name = models.CharField(max_length = 100, unique = True)
    course_code = models.CharField(max_length = 10, unique = True)
    course_dept = models.CharField(max_length = 100)
    course_credits = models.PositiveIntegerField()

class Grades(models.Model):
    '''
    A class of models that creates the database of grades, classified by student roll numbers.
    '''

    student = models.ForeignKey(Student, on_delete = models.CASCADE, related_name = 'stu_grades')
    semester_number = models.PositiveIntegerField()
    subject = models.ForeignKey(Courses, on_delete = models.CASCADE, related_name = 'sub_grades')

    GRADE_CHOICES = (
        (10, "EX"),
        (9, "A"),
        (8, "B"),
        (7, "C"),
        (6, "D"),
        (5, "P"),
        (0, "F"),
        (-1, "R")
    )
    
    grade = models.IntegerField(choices = GRADE_CHOICES, default = -1, null = True, blank = True)
    is_backlog = models.BooleanField(default = False)
    is_cleared = models.BooleanField(default = False)
    number_of_courses = models.PositiveIntegerField(default = 0)

    class Meta:

        unique_together = ('semester_number', 'student', 'subject')

class GradeTally(models.Model):
    '''
    Class of models that store the credit and GPA information fro eacch student.
    '''

    student = models.ForeignKey(Student, on_delete = models.CASCADE, related_name = 'stu_tally')
    semester_number = models.PositiveIntegerField()
    sgpa = models.FloatField()
    cgpa = models.FloatField()
    total_creds = models.PositiveIntegerField()

    class Meta:

        unique_together = ('semester_number', 'student')
    
    

inventory/forms.py
from django import forms
from .models import Inventory

class InventoryForm(forms.ModelForm):
    '''
    A form to enter the details of a new furniture type
    '''

    furniture_name = forms.CharField(max_length = 200, required = True, widget=forms.TextInput(attrs={'placeholder': 'Furniture Name'})) #Name of the inven
    dept_name = forms.CharField(max_length = 200, required = True, widget=forms.TextInput(attrs={'placeholder': 'Department Name'})) #For the storage of different department names.
    furniture_type = forms.CharField(max_length = 200, widget=forms.TextInput(attrs={'placeholder': 'Furniture Type'})) #The head of the inven, whom a student has to contact.
    price = forms.IntegerField(min_value = 0, required = True, widget=forms.TextInput(attrs={'placeholder': 'Price (in Rs)'}))
    quantity = forms.IntegerField(min_value = 0, required = True, widget=forms.TextInput(attrs={'placeholder': 'Quantity'}))
    location = forms.CharField(max_length = 200, required = True, widget=forms.TextInput(attrs={'placeholder': 'Location'})) #Name of the location

    class Meta:

        model = Inventory
        fields = '__all__'

    def save(self):

        inven = super(InventoryForm, self).save(commit = False)

        inven.furniture_name = self.cleaned_data.get('furniture_name')
        inven.dept_name = self.cleaned_data.get('dept_name')
        inven.furniture_type = self.cleaned_data.get('furniture_type')
        inven.price = self.cleaned_data.get('price')
        inven.quantity = self.cleaned_data.get('quantity')
        inven.location = self.cleaned_data.get('location')

        try:
            inven.save()

        except Exception:

            Inventory.objects.filter(id = inven.id).delete()
            inven.save()

        return inven

templates/home/home-faculty.html
{% extends 'home/home.html' %}

{% block redirect %}

{% if not user.is_faculty %} 
<meta http-equiv="refresh" content="0; URL={% url 'home' %}" />
{% endif %}

{% endblock %}

{% block content %}

{% if user.is_faculty %}
<h2> Faculty View </h2>
<p> Hello Faculty! </p>
{% endif %}

{% endblock content %}

templates/home/home-secretary.html
{% extends 'home/home.html' %}

{% block redirect %}

{% if not user.is_secretary %} 
<meta http-equiv="refresh" content="0; URL={% url 'home' %}" />
{% endif %}

{% endblock %}

{% if user.is_secretary %}

{% block register %}
<li>
  <div class="dropdown">
      <button type="button" class="dropbtn">Register New Users
        <i class="fa fa-caret-down"></i>
      </button>
      <div class="dropdown-content">
        <a href="{% url 'student_register' %}">Register New Student</a>
        <a href="{% url 'faculty_register' %}">Register New Teacher</a>
        <a href="{% url 'secretary_register' %}">Register New Secretary</a>
      </div>
  </div>
</li>
{% endblock register %}

{% block content %}

<h2> Secretary View </h2> <br>
<p> Hello Secretary! </p> <br>

{% endblock content %}

{% endif %}

templates/home/home-student.html
{% extends 'home/home.html' %}

{% block redirect %}

{% if not user.is_student %} 
<meta http-equiv="refresh" content="0; URL={% url 'home' %}" />
{% endif %}

{% endblock %}

{% block content %}

{% if user.is_student %}
<h2> Student View </h2>
<p> Hello Student! </p>
{% endif %}

{% endblock content %}

templates/home/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MIT UDIS</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css" />
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v2.1.6/css/unicons.css">
    <link rel="stylesheet" href="{% static 'styles/profile-style.css'%}">
</head>

<body>
    <h1>
        Student Profile
    </h1>
    <div class="student-profile py-4">
        
        

        {% if student %}

        <div class="container">
            <a href="{% url 'home' %}" class="button" style="text-align: center;color: brown;font-size: 25px;">Home</a>
            {% if user.is_secretary %}<td><a href="{% url 'grade_tally' student.id %}" style="text-align: center;color: brown;font-size: 25px; margin-left: 20px;">Tally Grades</a></td>{% endif %}
            {% if messages %}
                {% for message in messages %}
                    <p style="text-align: center;color: brown;">{{ message }}</p>
                {% endfor %}
            {% endif %}
            <div class="row">
                <div class="col-lg-4">
                    <div class="card shadow-sm">
                        <div class="card-header bg-transparent text-center">
                            <img class="profile_img" src="/static/user.png" alt="">
                            <h3>{{ student.user.first_name }} {{ student.user.last_name }}</h3>
                        </div>
                        <div class="card-body">
                            <p class="mb-0"><strong class="pr-1">Department:</strong>{{ student.user.dept_name }}</p>
                            <p class="mb-0"><strong class="pr-1">Course:</strong>{{ student.get_programme_display }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <div class="card shadow-sm">
                        <div class="card-header bg-transparent border-0">
                            <h2 class="mb-0"><i class="uil uil-cloud-info"></i></i>General Information</h2>
                        </div>
                        <div class="card-body pt-0">
                            <table class="table table-bordered">
                                <tr>
                                    <th width="30%">Roll number</th>
                                    <td width="2%">:</td>
                                    <td>{{ student.user.username }}</td>
                                </tr>
                                <tr>
                                    <th width="30%">Address</th>
                                    <td width="2%">:</td>
                                    <td>{{ student.user.address }}</td>
                                </tr>
                                <tr>
                                    <th width="30%">Gender</th>
                                    <td width="2%">:</td>
                                    <td>{{ student.user.get_gender_display }}</td>
                                </tr>
                                <tr>
                                    <th width="30%">Year of Joining</th>
                                    <td width="2%">:</td>
                                    <td>{{ student.user.year_of_admission }}</td>
                                </tr>
                                <tr>
                                    <th width="30%">CGPA</th>
                                    <td width="2%">:</td>
                                    <td>{{ student.stu_tally.last.cgpa }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="performance">
                    <div class="card shadow-sm">
                        <div class="card-header bg-transparent border-0">
                            <h2 class="mb-0"><i class="uil uil-graduation-cap"></i>Performance</h2>
                        </div>
                        <br>
                        <div class="container">
                            <!-- Add all the database tables here -->
                            <div class="backlog">
                                <h3>
                                    Backlogged Courses
                                </h3>
                                <table>
                                    <thead>
                                        <tr>
                                            <th>S.No</th>
                                            <th>Course code</th>
                                            <th>Course Name</th>
                                            <th>Department</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for grade in distinct %}
                                        {% if grade.is_backlog %}
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ grade.subject.course_code }}</td>
                                            <td>{{ grade.subject.course_name }}</td>
                                            <td>{{ grade.subject.course_dept }}</td>
                                        </tr>
                                        {% endif %}
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <br><br><br>
                            {% regroup student.stu_grades.all|dictsort:"semester_number" by semester_number as grade_list %}
                            <div class="sgpa">
                                <h3>
                                    Semester Wise Performance
                                </h3>
                                <br>
                                {% for grouper, grade in grade_list %}
                                <h4>Semester-{{ grouper }}</h4>
                                <table>
                                    <thead>
                                        <tr>
                                            <th>S.No</th>
                                            <th>Course code</th>
                                            <th>Course Name</th>
                                            <th>Credits</th>
                                            <th>Grade</th>
                                            {% if user.is_secretary %}<th>Update Grade</th>{% endif %}
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for g in grade %}
                                        
                                        <tr>
                                            <td>{{ forloop.counter }}</td>
                                            <td>{{ g.subject.course_code }}</td>
                                            <td>{% if g.is_backlog and g.is_cleared %}*{% endif %}{{ g.subject.course_name }}</td>
                                            <td>{{ g.subject.course_credits }}</td>
                                            <td>{{ g.get_grade_display }}</td>
                                            {% if user.is_secretary %}<td><a href="{% url 'grade_update' g.id %}">Update Grade</a></td>{% endif %}
                                        </tr>
                                        {% endfor%}
                                    </tbody>
                                </table>
                                <br>
                                <table>
                                    <thead>
                                        <tr>
                                            <th>Total Credits</th>
                                            <th>SGPA</th>
                                            <th>CGPA</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for tal in student.stu_tally.all %}
                    
                                        {% if tal.semester_number == grouper %}
                                        <tr>
                                            <td>{{ tal.total_creds }}</td>
                                            <td>{{ tal.sgpa }}</td>
                                            <td>{{ tal.cgpa }}</td>
                                        </tr>
                                        {% endif %}
                                        {% endfor %}
                                        
                                    </tbody>
                                </table>
                                <br><br>
                                {% endfor %}
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <p>Oops! It seems there is no data satisfying all the conditions together!</p>
        {% endif %}
    </div>
</body>

</html>

templates/home/searchstu.html
{% load static %}

<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Student</title>

    {% if not user.is_secretary and not user.is_faculty %} 
    <meta http-equiv="refresh" content="0; URL={% url 'stuprofile' %}" />
    {% endif %}

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/proj-style.css' %}">
</head>


<body class="cont">
    <div>
        <a href="{% url 'home' %}" class="button">Home</a>
        
        <h1>Results for Search Student</h1>
        
    </div>
    
    {% if students %}

    <div class="table-container">
            
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}

        <table>
            <thead>
                <tr>
                    <th>Student Name</th>

                    {% if user.is_secretary or user.is_faculty %} 
                        <th>Details</th>
                    {% endif %}

                </tr>
            </thead>
            <tbody>

                {% for student in students %}

                <tr>
                    <td>{{ student.first_name }} {{ student.last_name }}</td>
                    
                    {% if user.is_secretary or user.is_faculty %} 
                        <td>
                            <a href="{% url 'search_stu_result' student.id %}">Details of {{ student.user.first_name }}</a>
                        </td>
                    {% endif %}
                    
                </tr>
                {% endfor %}

                

            </tbody>
        </table>
        {% else %}
            
            <p>Oops! It seems there is no data satisfying all the conditions together!</p>

        {% endif %}
    </div>

</body>

</html>

templates/home/student-search.html
{% load static %}

<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Student</title>

    {% if not user.is_authenticated %} 
    <meta http-equiv="refresh" content="0; URL={% url 'home' %}" />

    {% elif user.is_student %}
    <meta http-equiv="refresh" content="0; URL={% url 'search_stu_result' user.stu.id %}" />
    {% endif %}

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/proj-style.css' %}">
</head>


<body class="cont">
    <div>
        <a href="{% url 'home' %}" class="button">Home</a>
        
        <h1>Search Student</h1>
        <h4>Enter required search data in the fields. If blank, the specific field queries all the students in the database.</h4>

    </div>
    <div class="container">
           
        {% if messages %}
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        {% endif %}
               
        <form action="{% url 'search_stu' %}" method="GET" class="project">

            <label for="id_roll_no">Enter the Roll number of the student:</label>
            <input name="r_no" type="text" placeholder="Enter the roll number (optional)"/>

            <label for="id_furniture_type">Enter the first name of the student:</label>
            <input name="stu_name" type="text" placeholder="Enter the first name here (optional)"/>

            <button type="submit" class="submit">Submit</button>
        </form>
        
    </div>

</body>

</html>