UDIS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name = 'home'),
    path('', include('accounts.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', views.home, name = 'home'),
    path('projects/', include('projects.urls')),
    path('inven/', include('inventory.urls')),
    path('pubs/', include('publications.urls')),
    path('accounts/', include('accountings.urls')),
    path('courses/', include('courses.urls'))
]

accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('login/', views.login_user, name = 'login_user'),
	path('logout/', views.logout_user, name = 'logout_user'),
        path('student/home/', views.student_home, name = 'student_home'),
        path('faculty/home/', views.faculty_home, name = 'faculty_home'),
        path('secretary/home/', views.secretary_home, name = 'secretary_home'),
	path('student-register/', views.StudentRegister.as_view(), name = 'student_register'),
	path('faculty-register/', views.FacultyRegister.as_view(), name = 'faculty_register'),
        path('secretary-register/', views.SecretaryRegister.as_view(), name = 'secretary_register'),
        path('student/search/', views.student_searcher, name = 'stusearch'),
        path('student/active-grades/<int:pk>', views.StudentActiveSearch.as_view(), name = 'active_grades'),
        path('student/search-result/', views.StudentSearchTable.as_view(), name = 'search_stu'),
        path('student/search-result/<int:pk>', views.StudentSearch.as_view(), name = 'search_stu_result'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    '''
    The extension of the abstractuser class, that defines boolean fields to
    distinguish between user classes. Stored as an SQL table in Postgres
    '''

    email = models.EmailField(unique = True)
    is_student = models.BooleanField(default = False)
    is_faculty = models.BooleanField(default = False)
    is_secretary = models.BooleanField(default = False)

    first_name = models.CharField(max_length = 80)
    last_name = models.CharField(max_length = 80)
    dept_name = models.CharField(max_length = 80)
    address = models.CharField(max_length = 200)

    GENDER_CHOICES = (
        ('', 'Select a gender'),
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Others')
    )
    
    gender = models.CharField(max_length = 1, choices = GENDER_CHOICES, default = '')
    phone_number = models.CharField(max_length = 10)
    year_of_admission = models.PositiveIntegerField(null = True, blank = True)
    
class Student(User):
    '''
    Class Student, that extends on the defined abstract User class
    '''

    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True, related_name = 'stu')

    PROGRAMME_CHOICES = (
        ('', 'Select a Programme'),
        ('BT', "Bachelor of Technology"),
        ('MT', "Master of Technology"),
        ('PhD', "Doctor of Philosophy"),
        ('MSc', "Master of Science"),
        ('BSc', "Bachelor of Science"),
        ('DD', "Dual Degree"),
    )
    programme = models.CharField(max_length = 3, choices = PROGRAMME_CHOICES, default = '')
    guardian_name = models.CharField(max_length = 80)
    


    
    

accountings/forms.py
from django import forms
from .models import Accounts

class TransactionForm(forms.ModelForm):

    amount = forms.IntegerField(min_value = 0, required = True, widget=forms.TextInput(attrs={'placeholder': 'Transaction amount (in Rs)'}))
    dept_name = forms.CharField(max_length = 200, required = True, widget=forms.TextInput(attrs={'placeholder': 'Department Name'}))
    transaction_type = forms.ChoiceField(required = True, choices = Accounts.TYPE_CHOICES)
    transactee = forms.CharField(max_length = 200, required = True, widget=forms.TextInput(attrs={'placeholder': 'Transactee name'}))
    purpose = forms.CharField(required = True, max_length = 500, widget=forms.TextInput(attrs={'placeholder': 'Please enter the purpose'}))
    date_of_transaction = forms.DateField(required = True)
    current_balance = forms.IntegerField(required = False)

    class Meta:
        model = Accounts
        fields = '__all__'

    def save(self):

        account = super(TransactionForm, self).save(commit = False)

        account.amount = self.cleaned_data.get('amount')
        account.dept_name = self.cleaned_data.get('dept_name')
        account.transaction_type = self.cleaned_data.get('transaction_type')
        account.transactee = self.cleaned_data.get('transactee')
        account.purpose = self.cleaned_data.get('purpose')
        account.date_of_transaction = self.cleaned_data.get('date_of_transaction')
        cur_amt = 0

        try:
            cur_obj = Accounts.objects.filter(dept_name = account.dept_name).last()
            cur_amt = cur_obj.current_balance

        except Exception:
            cur_amt = 0
        
        if account.transaction_type == 'C': account.current_balance = account.amount + cur_amt
        else: account.current_balance = cur_amt - account.amount

        try:
            account.save()
        except Exception:
            Accounts.objects.filter(id = account.id).delete()
            account.save()

        return account
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.views.generic import CreateView, ListView, DetailView
from django.core.exceptions import PermissionDenied

from .models import User, Student
from courses.models import Grades
from .forms import StudentSignUpForm, FacultySignUpForm, SecretarySignUpForm

# Create your views here.

def home(request):
    return render(request, 'home/home.html')

def student_searcher(request):
    return render(request, 'home/student-search.html')

def student_home(request):
    return render(request, 'home/home-student.html')

def faculty_home(request):
    return render(request, 'home/home-faculty.html')

def secretary_home(request):
    return render(request, 'home/home-secretary.html')

def student_regcomplete(request):
    student = Student.objects.all().last()
    return render(request, 'student_regComplete.html', {"student": student})

def faculty_regcomplete(request):
    faculty = User.objects.all().last()
    return render(request, 'fac_regComplete.html', {"faculty": faculty})

def secretary_regcomplete(request):
    secretary = User.objects.all().last()
    return render(request, 'sec_regComplete.html', {"secretary": secretary})

def stu_user_validate(roll_number):

    if len(roll_number) != 9: return False

    if not '0' <= roll_number[:2] <= '99':
        return False
    elif not 'AA' <= roll_number[2:4] <= 'ZZ':
        return False
    elif not '00000' <= roll_number[4:] <= '99999':
        return False
    else:
        return True

class StudentRegister(CreateView):

    model = User
    form_class = StudentSignUpForm
    template_name = 'registers/student_register.html'

    def form_valid(self, form):
        
        em = form.cleaned_data.get('email')
        #if not stu_user_validate(form.cleaned_data['username']):
        #    messages.error(self.request, "Roll number is not in the correct format!")
        #    return render(self.request, 'registers/student_register.html', {'form': form})

        if User.objects.filter(email = em).exists():
            messages.error(self.request, "User with the given email ID already exists!")
            return render(self.request, 'registers/student_register.html', {'form': form})
        
        user = form.save()
        
        if user:
            messages.success(self.request, f'Student {user.first_name} {user.last_name} added successfully!')
            return redirect('secretary_home')

class StudentSearchTable(ListView):

    model = Student
    template_name = 'home/searchstu.html'
    context_object_name = 'students'

    def get_queryset(self):
        
        roll = self.request.GET.get('r_no')
        stu_name = self.request.GET.get('stu_name')

        if roll == '':
            if stu_name == '':
                user = Student.objects.all()
            
            else:
                user = Student.objects.filter(user__first_name = stu_name)
        else:
            if stu_name == '':
                user = Student.objects.filter(user__username = roll)
            
            else:
                user = Student.objects.filter(user__username = roll, user__first_name = stu_name)
        return user

class StudentSearch(DetailView):

    model = Student
    template_name = 'home/profile.html'
    context_object_name = 'student'
    extra_context = {'distinct': Grades.objects.all().distinct('subject__course_name')}

    def dispatch(self, request, *args, **kwargs):
        user_obj = request.user
        if not (user_obj.username == self.get_object().username or user_obj.is_faculty or user_obj.is_secretary):
            raise PermissionDenied
        return super().dispatch(request,*args,**kwargs)

class StudentActiveSearch(DetailView):
    model = Student
    template_name = 'grades/grades.html'
    context_object_name = 'student'
    extra_context = {'distinct': Grades.objects.all().distinct('subject__course_name')}

    def dispatch(self, request, *args, **kwargs):
        user_obj = request.user
        if not user_obj.username == self.get_object().username:
            raise PermissionDenied
        return super().dispatch(request,*args,**kwargs)
    
class FacultyRegister(CreateView):

    model = User
    form_class = FacultySignUpForm
    template_name = 'registers/faculty_register.html'

    def form_valid(self, form):
        
        em = form.cleaned_data.get('email_id')

        if User.objects.filter(email = em).exists():
            messages.error(self.request, "User with the given email ID already exists!")
            return render(self.request, 'registers/faculty_register.html', {'form': form})
        
        user = form.save()

        if user:
            messages.success(self.request, f'Faculty {user.first_name} {user.last_name} added successfully!')
            return redirect('secretary_home')

class SecretaryRegister(CreateView):

    model = User
    form_class = SecretarySignUpForm
    template_name = 'registers/secretary_register.html'
    
    def form_valid(self, form):
        
        em = form.cleaned_data.get('email_id')

        if User.objects.filter(email = em).exists():
            messages.error(self.request, "User with the given email ID already exists!")
            return render(self.request, 'registers/secretary_register.html', {'form': form})
        
        user = form.save()

        if user:
            messages.success(self.request, f'Secretary {user.first_name} {user.last_name} added successfully!')
            return redirect('secretary_home')   
            
def login_user(request):

    if request.method == 'POST':

        form = AuthenticationForm(data = request.POST)
        if form.is_valid():

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username = username, password = password)
            if user is not None:

                login(request, user)

                if user.is_student:
                    return redirect('/student/home')
                elif user.is_faculty:
                    return redirect('/faculty/home')
                elif user.is_secretary:
                    return redirect('/secretary/home')
                else:
                    return redirect('/home')
            else:
                messages.error(request, "Invalid username or password")

        else:
            messages.error(request, "Invalid username or password")

    return render(request, 'login.html', context = {'form': AuthenticationForm()})

def logout_user(request):

    logout(request)
    return redirect('/')

templates/accounts/accounts.html
{% load static %}

<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accounts</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/proj-style.css' %}">
</head>


<body class="cont">

    <div>
        <a href="{% url 'home' %}" class="button">Home</a>
        {% if user.is_secretary %} <a href="{% url 'addacc' %}" class="button">Add Transaction</a> {% endif %}
        {% if user.is_authenticated %}
        <h1>Accounts of the department {{ user.dept_name }}</h1>
        {% else %}
        <h1>Accounts of the University</h1>
        {% endif %}

        <div class="table-container">
            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}

            <table>
                <thead>
                    <tr>
                        {% if not user.is_authenticated %} <th>Department</th>{% endif %}
                        <th>Transaction Amount</th>
                        <th>Transaction Type</th>
                        <th>Transactee</th>
                        <th>Date of Transaction</th>
                        <th>Purpose</th>
                        <th>Balance</th>

                    </tr>
                </thead>
                <tbody>

                    {% for transaction in accounts %}

                        <tr>
                            {% if not user.is_authenticated %} <td>{{ transaction.dept_name }}</td>{% endif %}
                            <td>{{ transaction.amount }}</td>

                            <td>{{ transaction.transaction_type }}</td>

                            <td>{{ transaction.transactee }}</td>

                            <td>{{ transaction.date_of_transaction }}</td>
 
                            <td>{{ transaction.purpose }}</td>

                            <td>{{ transaction.current_balance }}</td>
                        </tr>

                    {% endfor %}
                    
                </tbody>
            </table>
        
        </div>
    </div>

</body>

</html>

templates/accounts/addaccount.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% if not user.is_secretary %} 
    <meta http-equiv="refresh" content="0; URL={% url 'allaccounts' %}" />
    {% endif %}
    
    <title>Add Project</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Abhaya+Libre:wght@800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styles/proj-style.css' %}">
</head>

<body>
    <div class="container">

        <form method="POST" class = "project">
            
            {% csrf_token %}
    
            <label for="id_dept_name">Department name:</label>

            {{ form.dept_name }}
            {{ form.dept_name.errors }}

            <label for="id_amount">Amount:</label>

            {{ form.amount }}
            {{ form.amount.errors }}
            
            <label for="id_transaction_type">Transaction Type:</label>
            
            {{ form.transaction_type }}
            {{ form.transaction_type.errors }}
    
            <label for="id_transactee">Transactee:</label>
    
            {{ form.transactee }}
            {{ form.transactee.errors }}

            <label for="id_purpose">Purpose:</label>
    
            {{ form.purpose }}
            {{ form.purpose.errors }}

            <label for="id_date_of_transaction">Date Of Transaction:</label>
    
            {{ form.date_of_transaction }}
            {{ form.date_of_transaction.errors }}
    
            <button type="submit" class = "submit">Submit!</button>

            {% if messages %}
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            {% endif %}
        </form>
    </div>
</body>

</html>